### ISSUE TITLE
수정하기 안 됨

### ISSUE THREAD

**Issue by yoodongbin** [yoodongbin/make-mini-board#24]

**Comment by yoodongbin** [comment]
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "login_info.name" (template: "fragment/main_header" - line 61, col 75)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393)
	at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230)
	... 48 common frames omitted
